file_name: "test.pickle"

batch_size: 32
language: English
treebank_name: merge
batch_first: True
quality_limit: 0.2

# These are pretty much default values
len_sorted: True
max_chars: 2048
max_tokens: 256
remove_duplicates: True
remove_unique_lemma_scripts: False
return_tokens_raw: True

hydra:
  run:
    dir: .
  output_subdir: null
  sweep:
    dir: .
    subdir: .