defaults:
  - default_train
  - model: udpipe2
  - preprocessor: udpipe2
  - _self_

experiment_name: UDPipe2
architecture: udpipe2

data:
  language: English
  treebank_name: ATIS
  batch_first: False
  len_sorted: True
  batch_size: 32
  source: ./morphological_tagging/data/um-treebanks-v2.9
  dataloader_kwargs:
    use_pytorch: False
    max_tokens: 5000
    max_batch_size: 512

trainer:
  gradient_clip_val: 2
  max_epochs: 60
  num_sanity_val_steps: 0
