data:
  language: English
  name: PUD
  splits: False
  FastText: True

model:
  c2w_kwargs:
    embedding_dim: 256
    h_dim: 256
    out_dim: 256
    bidirectional: True
  w_embedding_dim: 512
  udpipe_rnn_dim: 512
  udpipe_bidirectional: True
  dropout_p: 0.5
  token_mask_p: 0.2
  label_smoothing: 0.03
  lr: 1.0e-3
  betas:
    - 0.9
    - 0.99

trainer:
  gradient_clip_val: 10
  max_epochs: 1


misc_hparams:
  use_scheduler: False
  batch_size: 4

logging:
  logger: wandb
  logger_kwargs:
    log_model: True
  monitor: lemma_valid_acc
  monitor_mode: 'max'

run:
  experiment_name: UDPipe2
  seed: 610
  gpu: 1
  deterministic: False
  debug: True
  fdev_run: 10
  prog_bar_refresh_rate: 1
