defaults:
  - _self_
  - langs: Dutch

print_hparams: True

gpu: 1
seed: 610
deterministic: True

src_lang: en

model:
  architecture: udpipe2

batch_size: 128

affix: test

parallel_dataset:
  tatoeba: True
  flores:
    split: all

hydra:
  run:
    dir: .
  output_subdir: null
  sweep:
    dir: .
    subdir: .
