defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

print_hparams: False
prog_bar_refresh_rate: 200

seed: 610
gpu: 1
deterministic: False
debug: False
fdev_run: False

logging:
  logger: wandb

hydra:
  run:
    dir: .
  output_subdir: null
  sweep:
    dir: .
    subdir: .
