defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

src_lang: English
tgt_lang: Czech

corpora:
  - gnome
  - ubuntu
  - kde4
  - eubookshop
  - opensubtitles
  - ted2020
  - globalvoices

test_size: 0.2
seed: 610
deterministic: true

agg_name: ataman_multidomain

index:
  index_level: tag_set
  filter_level: script
  reduce:
    max_samples: null
    min_samples: 0
    min_lemmas: 2
    min_samples_per_lemma: 2

hydra:
  run:
    dir: .
  output_subdir: null
  sweep:
    dir: .
    subdir: .
