defaults:
  - default_train
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

gpu: 1

experiment_name: nmt_adapt_test

print_hparams: True
debug: False
sanity_check: True
save_every_n: null

epochs: 25

logging:
  logger_kwargs:
    job_type: test_multitask
    mode: online

data:
  src_lang: English
  tgt_lang: Czech
  dataset_name: ataman_multidomain

trainer:
  model_name: Helsinki-NLP/opus-mt-en-cs
  nmt_kwargs:
    label_smoothing: 0.1
  morph_tag_clf_kwargs:
    layer_dropout: 0.1
    hidden_dim: 256
    label_smoothing: 0.1
  optimizer: adam
  optimizer_kwargs:
      nmt_lr: 3e-5
      clf_lr: 1e-3
      betas:
        - 0.9
        - 0.98
      weight_decay: 1e-2
      grad_norm: 5
  optimizer_scheduler: inv_sqrt
  optimizer_scheduler_kwargs:
      n_warmup_steps: 1000

data_loader:
  max_tokens: 1024
  max_sents: 128
