defaults:
  - default_train
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

experiment_name: nmt_adapt

print_hparams: True
debug: False
gpu: 1
sanity_check: true

patience: 10
lr_reduce: 1.0
save_every_n: 1

epochs: 10
steps_per_epoch: 5000

logging:
  logger_kwargs:
    job_type: test
    mode: online
    project: nmt_adapt_test

data:
  src_lang: english
  tgt_lang: czech
  dataset_name: ataman_multidomain

index:
  fp: "./nmt_adapt/data/indices/ataman_multidomain_english_czech"
  infer_splits: True
  filter:
    - "_"

task_sampler:
  eval_fp: "./nmt_adapt/eval/220426_1444_English_Czech.pickle"

trainer:
  model_name: "Helsinki-NLP/opus-mt-en-cs"
  meta_learner_algorithm: "anil"
  inner_lr: 1.0e-3
  meta_lr: 5.0e-6
  meta_optimizer_algorithm: adamw
  meta_optimizer_kwargs:
    weight_decay: 1.0e-1
    betas:
      - 0.9
      - 0.999
  meta_optimizer_scheduler: linear
  meta_optimizer_scheduler_kwargs:
    n_warmup_steps: 20000
  train_meta_batchsize: 8
  valid_meta_batchsize: 1024
  train_k: 1
  valid_k: 1
  first_order_epochs: 0
  grad_clip_val: 2.0
  grad_clip_norm: 5.0

data_loader:
  mode: cross_transfer
  n_lemmas_per_task: 4
  n_samples_per_lemma: 2
  p_full_nmt: 0.50
  p_uninformed: 0.00
  eval_uninformed: False
