defaults:
  - default_train
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

gpu: 1

experiment_name: nmt_adapt_test

baseline: fine_tune

print_hparams: True
debug: False
sanity_check: True
save_every_n: null

epochs: 1

logging:
  logger_kwargs:
    job_type: test_finetune
    mode: online
    project: nmt_adapt_baselines

data:
  src_lang: English
  tgt_lang: Czech
  dataset_name: ataman_multidomain

trainer:
  model_name: Helsinki-NLP/opus-mt-en-cs
  nmt_kwargs:
    label_smoothing: 0.1
    dropout: 0.1
    seq_mask: 0.0
  optimizer_algorithm: adamw
  optimizer_kwargs:
    nmt_lr: 1e-5
    betas:
      - 0.9
      - 0.98
    weight_decay: 1e-2
    grad_val: 2.0
    grad_norm: 5.0
  optimizer_scheduler: inv_sqrt
  optimizer_scheduler_kwargs:
    n_warmup_steps: 0.08

data_loader:
  max_tokens: 512
  max_sents: 128
  length_sort: False
  max_tokens_valid: 1024
