defaults:
  - default_train
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

experiment_name: nmt_adapt_test

print_hparams: True
debug: False
gpu: 1
sanity_check: true
save_every_n: null

epochs: 100
steps_per_epoch: 250

logging:
  logger_kwargs:
    job_type: test

data:
  src_lang: english
  tgt_lang: czech
  dataset_name: ataman_multidomain

index:
  fp: "./nmt_adapt/data/indices/ataman_multidomain_english_czech"
  infer_splits: True
  index_level: tag_set
  filter_level: script
  #reduce:
  #  max_samples: 1000
  #  min_samples: 0
  #  min_lemmas: 2
  #  min_samples_per_lemma: 2
  filter:
    - "_"

task_sampler:
  eval_fp: "./nmt_adapt/eval/220426_1444_English_Czech.pickle"
  filter_level: script

trainer:
  model_name: "Helsinki-NLP/opus-mt-en-cs"
  meta_learner_algorithm: "anil"
  inner_lr: 5.0e-4
  meta_optimizer_algorithm: adamw
  meta_lr: 1.0e-5
  meta_optimizer_kwargs:
    weight_decay: 1.0e-2
  meta_optimizer_scheduler: inv_sqrt
  meta_optimizer_scheduler_kwargs:
    n_warmup_steps: 0.04
  train_meta_batchsize: 8
  valid_meta_batchsize: 256
  train_k: 1
  valid_k: 1
  first_order_epochs: 0
  grad_clip_val: 2.0

data_loader:
  mode: cross_transfer
  n_lemmas_per_task: 2
  n_samples_per_lemma: 4
  p_full_nmt: 0.1
  p_uninformed: 0.1
  eval_uninformed: False
