defaults:
  - default_train
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

gpu: 1

experiment_name: nmt_adapt_test

baseline: multi_task_morph_tag

print_hparams: True
debug: False
sanity_check: True

cutoff: null
valid_size: 0.1
max_steps: 100000
eval_every_n_steps: 10000
patience: 3
lr_reduce: 0.5
save_every_n: null

logging:
  logger_kwargs:
    job_type: test_multi_task_morph_tag
    mode: online
    project: nmt_adapt_baselines

data:
  src_lang: English
  tgt_lang: Czech
  dataset_name: ataman_multidomain

trainer:
  model_name: Helsinki-NLP/opus-mt-en-cs
  nmt_kwargs:
    label_smoothing: 0.1
    dropout: 0.1
    seq_mask: 0.0
  morph_tag_clf_kwargs:
    layer_dropout: 0.2
    dropout: 0.2
    hidden_dim: 256
    label_smoothing: 0.1
  optimizer_algorithm: adamw
  optimizer_kwargs:
    nmt_lr: 1e-6
    clf_lr: 5e-4
    betas:
      - 0.9
      - 0.98
    weight_decay: 1e-2
    grad_val: 2.0
    grad_norm: 5.0
  optimizer_scheduler: inv_sqrt
  optimizer_scheduler_kwargs:
    n_warmup_steps: 16000

data_loader:
  max_tokens: 512
  max_sents: 128
  length_sort: False
  max_tokens_valid: 1024
