# @package _global_

tgt_lang: Czech

treebank_data_module_file_path: ./morphological_tagging/data/corpora/Czech_merge_0.2_False.pickle

model:
  tagger_checkpoint_file_path: ./morphological_tagging/checkpoints/UDPipe2_Czech_merge/version_1/checkpoints/last.ckpt
