# @package _global_

tgt_lang: ru

treebank_data_module_file_path: ./morphological_tagging/data/corpora/Russian_merge_0.2_False.pickle

model:
  tagger_checkpoint_file_path: ./morphological_tagging/checkpoints/UDPipe2_Russian_merge/version_1/checkpoints/last.ckpt
